routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//登陆 登出 注册 视图和操作

// Password Reset Routes...
//Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
//Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
//Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
//Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
//Route::get('auth/reset/pass', 'IndexController@resetFormPage')->name('password.request');

Route::middleware(['check.install.status', 'throttle:60,1'])->group(function () {//安装路由
    //Install
    Route::get('install/init', 'InstallController@installPage'); //Install View
    Route::post('install/init', 'InstallController@installAction');//Install Action
});


Route::middleware(['throttle:60,1','check.install.status'])->group(function () {
    Route::get('/', "IndexController@indexPage");//首页视图
    //Goods Show Page
    Route::get('goods/show', 'IndexController@goodShowPage')->name('good.show');//商品列表Goods Show Page
    //User email　validate
    Route::get('user/email/validate/{id}/{token}','IndexController@userEmailTokenValidate')->where(['id' => '^[0-9]*$']);
    //Diy page view
    Route::get('page/{hash}','DiyPageController@indexPage')->name('diy_page');
});

Route::middleware(['guest','throttle:60,1'])->group(function (){
    //Login
    Route::get('login', 'IndexController@loginPage')->name('login');//登陆视图 Login View
    Route::post('login', 'Auth\LoginController@login');//登陆操作 Login View
    //Register
    Route::get('register', 'IndexController@registerPage')->name('register');//注册视图 Register View
    Route::post('register', 'Auth\RegisterController@register');//注册操作 Register View
});
// wecaht/order/notify /alipay/order/notify /diy/order/notify
Route::any('/{payment}/order/notify', 'Payment\PayController@notify');//支付回调
Route::get('/temp/cron', "IndexController@tempCronAction");//临时监控

Route::prefix('admin')->group(function () {//管理路由
    Route::middleware(['auth', 'check.admin.authority', 'throttle:60,1'])->group(function () {
        Route::name('admin.')->group(function () {

            Route::get('/', 'AdminController@indexPage')->name('home');//Home Index View

            Route::prefix('user')->group(function () { //User Setting
                //Show
                Route::get('show', 'AdminController@userShowPage')->name('user.show');
                //Add
                Route::get('add', 'AdminController@userEditPage');
                Route::post('add', 'AdminController@userEditPage');
                //Edit
                Route::get('edit/{id}', 'AdminController@userEditPage')->name('user.edit');
                Route::post('edit', 'UserController@userEditAction');
            });

            Route::prefix('order')->group(function () { //订单 Order
                Route::get('show', 'AdminController@orderShowPage')->name('order.show');
                Route::get('edit/{no}', 'AdminController@orderEditPage')->name('order.edit');
                Route::post('edit', 'OrderController@orderEditAction');
            });
            Route::prefix('host')->group(function () { //主机 Host
                //Show
                Route::get('show', 'AdminController@hostShowPage')->name('host.show');
                //Recreate host action
                Route::post('create/host/re', 'HostController@reCreateHost')->where(['id' => '^[0-9]*$']);
                //Host Edit
                Route::get('detailed/{id}','AdminController@hostDetailedPage')->where(['id' => '^[0-9]*$'])->name('host.detailed');
                Route::post('detailed','HostController@hostEditAction');
                //host manager
                Route::post('open','HostController@openHost')->name('host.open');
                Route::post('close','HostController@closeHost')->name('host.close');
                Route::post('terminate','HostController@terminateHost')->name('host.terminate');
            });
            Route::prefix('work/order')->group(function () { //工单 Work order
                //show
                Route::get('show', 'AdminController@workOrderShowPage')->name('work.order.show');
                //Work order dateiled
                Route::get('detailed/{id}', 'AdminController@workOrderDetailedPage')->name('work.order.detailed')->where(['id' => '^[0-9]*$']);
                //Work order close
                Route::post('close', 'WorkOrderController@workOrderCloseAction')->name('work.order.close');
                //Work order reply
                Route::post('reply', 'WorkOrderController@workOrderAdminReplyAction')->name('work.order.reply');
            });
            Route::prefix('new')->group(function () { //新闻 news
                //show
                Route::get('show', 'AdminController@newShowPage')->name('new.show');
                //add
                Route::get('add', 'AdminController@newAddPage')->name('new.add');
                Route::post('add', 'NewController@newAddAction');
                //edit
                Route::get('edit/{id}', 'AdminController@newEditAction')->name('new.edit');
                Route::post('edit', 'NewController@newEditAction');
                //del
                Route::post('del', 'NewController@newDelAction')->name('new.del');
            });
            Route::prefix('good')->group(function () { //商品
                //Goods categories list
                Route::get('show', 'AdminController@goodShowPage')->name('good.show');
                //Goods categories add
                Route::get('categories/add', 'AdminController@goodCategoriesAddPage')->name('good.categories.add');
                Route::post('categories/add', 'GoodController@goodCategoriesAddAction');
                //Goods categories edit
                Route::get('categories/edit/{id}', 'AdminController@goodCategoriesEditPage')->name('good.categories.edit')->where(['id' => '^[0-9]*$']);
                Route::post('categories/edit', 'GoodController@goodCategoriesEditAction');
                //Goods categories del
                Route::post('categories/del', 'GoodController@goodCategoriesDelAction')->name('good.categories.del');
                //Goods configure add
                Route::get('configure/add/{type}', 'AdminController@goodConfigureAddPage')->name('good.configure.add');
                Route::post('configure/add', 'GoodConfigureController@goodConfigureAddAction');
                //Goods configure del
                Route::post('configure/del', 'GoodConfigureController@goodConfigureDelAction')->name('good.configure.del');
                //Goods configure edit
                Route::get('configure/edit/{id}', 'AdminController@goodConfigureEditPage')->name('good.configure.edit')->where(['id' => '^[0-9]*$']);
                Route::post('configure/edit', 'GoodConfigureController@goodConfigureEditAction');
                //Goods add
                Route::get('add', 'AdminController@goodAddPage')->name('good.add');
                Route::post('add', 'GoodController@goodAddAction');
                //Goods Edit
                Route::get('edit/{id}', 'AdminController@goodEditPage')->name('good.edit');
                Route::get('edit', 'AdminController@userEditPage');
                Route::post('edit', 'GoodController@goodEditAction');

                Route::get('charging/{id}','AdminController@goodChargingPage')->name('good.charging');
                Route::post('charging/edit','GoodController@goodChargingEdit')->name('good.charging.edit');
                Route::post('charging/add','GoodController@goodChargingAdd')->name('good.charging.add');
                Route::post('charging/del','GoodController@goodChargingDel')->name('good.charging.del');
                //Goods Del
                Route::post('del', 'GoodController@goodDelAction')->name('good.del');
            });

            Route::prefix('setting')->group(function () { //全局设置
                Route::get('/', 'AdminController@settingIndexPage')->name('setting.index');
                Route::post('/', 'AdminController@settingEditAction');
                //Payment Setting
                Route::get('{payment}/pay/config', 'AdminController@paymentPluginConfigPage')->name('setting.pay');
                Route::post('pay/config', 'Payment\PayController@paymentPluginConfigAction');
                //Mail Setting
                Route::get('mail/config','AdminController@mailDriveConfigPage')->name('setting.mail');
                Route::post('mail/config','MailDrive\UserMailController@mailDriveConfigAction');
                //Wechat Setting
                Route::get('wechat/config','AdminController@wechatConfigPage')->name('setting.wechat');
                Route::post('wechat/config','Wechat\WechatController@wechatConfigAction');
            });
            Route::prefix('server')->group(function () { //服务器设置
                //Show
                Route::get('show', 'AdminController@serverShowPage')->name('server.show');
                //Status
                Route::get('status/{id}', 'ServerController@serverStatusPage')->name('server.status')->where(['id' => '^[0-9]*$']);
                //Add
                Route::get('add', 'AdminController@serverAddPage')->name('server.add');
                Route::post('add', 'ServerController@serverAddAction');
                //Edit
                Route::get('edit/{id}', 'AdminController@serverEditPage')->name('server.edit')->where(['id' => '^[0-9]*$']);

resources/views/admin/themes/default/goods/add_categories.blade.php
@extends('admin.themes.default.layouts.app')

@section('content')
    @include('admin.themes.default.layouts.header')
@endsection

@section('container-fluid')
    <div class="row">
        <div class="col-xl-12 order-xl-1">
            <div class="card bg-secondary shadow">
                <div class="card-header bg-white border-0">
                    <div class="row align-items-center">
                        <div class="col-12">
                            <h3 class="mb-0">添加商品分组</h3>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <form method="post" id="add-form" action="{{url('/admin/good/categories/add')}}">
                        {{csrf_field()}}
                        <h6 class="heading-small text-muted mb-4">基础信息</h6>
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="input-username">分组标题</label>
                                        <input type="text" class="form-control form-control-alternative"
                                               placeholder="分组标题" value="{{old('title')}}" name="title">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label">分组简介</label>
                                        <input type="text" name="subtitle" class="form-control form-control-alternative"
                                               value="{{old('subtitle')}}" placeholder="可为空">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label">排序</label>
                                        <input type="text" name="level" class="form-control form-control-alternative"
                                               value="{{old('level') ? old('level'): 0}}" placeholder="值越大越靠前">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="input-email">显示</label>
                                        <select class="custom-select" id="inputGroupSelect02" name="display">
                                            <option value="1">显示</option>
                                            <option value="0">隐藏</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr class="my-4"/>
                        <h6 class="heading-small text-muted mb-4">更多信息</h6>
                        <div class="pl-lg-4">
                            <div class="form-group">
                                <label class="form-control-label" for="input-last-name">分组描述</label>
                                <textarea rows="4" name="content" class="form-control form-control-alternative"
                                          placeholder="可为空">{{old('content')}}</textarea>
                            </div>
                        </div>
                        @include('admin.themes.default.layouts.errors')
                        <input type="submit" class="btn btn-primary" value="新建">
                    </form>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/themes/default/goods/add_configure_diy.blade.php
@extends('admin.themes.default.layouts.app')

@section('content')
    @include('admin.themes.default.layouts.header')
@endsection

@section('container-fluid')
    <div class="row">
        <div class="col-xl-12 order-xl-1">
            <div class="card bg-secondary shadow">
                <div class="card-header bg-white border-0">
                    <div class="row align-items-center">
                        <div class="col-12">
                            <h3 class="mb-0">编辑插件配置</h3>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <form method="post" id="add-form" action="{{action('AdminController@paymentPluginConfigAction')}}">
                        {{csrf_field()}}
                        <input type="hidden" value="{{$payment}}" name="payment">
                        <h6 class="heading-small text-muted mb-4">支付插件配置信息</h6>
                        @if(!empty($form))
                            @foreach($form as $title=>$value)
                                <div class="pl-lg-4">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label class="form-control-label"
                                                       for="input-username">{{$title}}</label>
                                                <input type="text" class="form-control form-control-alternative"
                                                       value="{{old($title)? old($title):$setting->where('name',$value)->first()->value }}"
                                                       name={{$title}} >
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        @endif
                        @include('admin.themes.default.layouts.errors')
                        <input type="submit" class="btn btn-primary" value="保存">
                    </form>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/themes/default/goods/show.blade.php
@extends('admin.themes.default.layouts.app')

@section('content')
    @include('admin.themes.default.layouts.card')
@endsection

@section('container-fluid')
    <div class="row">
        <div class="col">
            <div class="card shadow">
                <div class="card-header border-0">
                    <h3 class="mb-0">商品列表</h3>
                </div>
                <div class="table-responsive">
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">商品名</th>
                            <th scope="col">销量</th>
                            <th scope="col">状态</th>
                            <th scope="col">分组</th>
                            <th scope="col">操作</th>
                            <th scope="col"></th>
                        </tr>
                        </thead>
                        <tbody>
                        @if(!empty($goods))
                            @foreach($goods as $item)
                                <tr>
                                    <th scope="row">
                                        <div class="media align-items-center">
                                            <div class="media-body">
                                                <span class="mb-0 text-sm">{{$item->title}}</span>
                                            </div>
                                        </div>
                                    </th>
                                    <td>
                                        {{$item->order->count()}}
                                    </td>
                                    <td>
                      <span class="badge badge-dot mr-4">
                        {{$item->status}}
                      </span>
                                    </td>

                                    <td>
                                        {{$item->categories_id}}
                                    </td>
                                    <td class="text-left">
                                        <div class="dropdown">
                                            <a class="btn btn-sm btn-icon-only text-light" href="#" role="button"
                                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="fas fa-ellipsis-v"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                <a class="dropdown-item"
                                                   href="{{route('admin.good.edit',['id'=>$item->id])}}">编辑</a>
                                                <a class="dropdown-item"
                                                   href="{{route('admin.good.charging',['id'=>$item->id])}}">计费管理</a>
                                                {{--<a class="dropdown-item"--}}
                                                {{--                                                   href="{{route('admin.good.edit',['id'=>$item->id])}}">下架</a>--}}
                                                <a class="dropdown-item" onclick="event.preventDefault();
                                                    document.getElementById('del-goods-{{$item->id}}').submit();"
                                                   href="">删除</a>

                                                <form id="del-goods-{{$item->id}}"
                                                      action="{{ route('admin.good.del') }}" method="POST"
                                                      style="display: none;">
                                                    {{csrf_field()}}
                                                    <input type="hidden" name="id" value="{{$item->id}}">
                                                </form>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
                <div class="card-footer py-4">
                    <a href="{{route('admin.good.add')}}" class="btn btn-primary">新增商品</a>
                    <button type="button" class="btn btn-secondary">新增自定义配置商品</button>
                </div>
            </div>
        </div>
    </div>
    <div class="row  mt-5">
        <div class="col-xl-6">
            <div class="card shadow">
                <div class="card-header border-0">
                    <h3 class="mb-0">商品分组</h3>
                </div>
                <div class="table-responsive">
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">分组名</th>
                            <th scope="col">商品数量</th>
                            <th scope="col">隐藏</th>
                            <th scope="col">排序</th>
                            <th scope="col">操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if(!empty($goods_categories))
                            @foreach($goods_categories as $categories)
                                <tr>
                                    <th scope="row">
                                        <div class="media align-items-center">
                                            <div class="media-body">
                                                <span class="mb-0 text-sm">{{$categories->title}}</span>
                                            </div>
                                        </div>
                                    </th>
                                    <td>
                                        {{$categories->getGood->count()}}
                                    </td>
                                    <td>
                      <span class="badge badge-dot mr-4">
                              {{$categories->display ?"显示":"隐藏"}}
                      </span>
                                    </td>

                                    <td>
                                        {{$categories->level}}
                                    </td>
                                    <td class="text-left">
                                        <div class="dropdown">
                                            <a class="btn btn-sm btn-icon-only text-light" href="#" role="button"
                                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="fas fa-ellipsis-v"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                <a class="dropdown-item"
                                                   href="{{route('admin.good.categories.edit',['id'=>$categories->id])}}">编辑</a>
                                                <a class="dropdown-item" onclick="event.preventDefault();
                                                    document.getElementById('del-goods-categories-{{$categories->id}}').submit();"
                                                   href="">删除</a>

                                                <form id="del-goods-categories-{{$categories->id}}"
                                                      action="{{ route('admin.good.categories.del') }}" method="POST"
                                                      style="display: none;">
                                                    {{csrf_field()}}
                                                    <input type="hidden" name="id" value="{{$categories->id}}">
                                                </form>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
                <div class="card-footer py-4">
                    <a href="{{route('admin.good.categories.add')}}" class="btn btn-primary">新增分组</a>
                </div>
            </div>
        </div>
        <div class="col-xl-6">
            <div class="card shadow">
                <div class="card-header border-0">
                    <h3 class="mb-0">商品配置</h3>
                </div>
                <div class="table-responsive">
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">分组名</th>
                            <th scope="col">商品数量</th>
                            <th scope="col">时长</th>
                            <th scope="col">操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if(!empty($goodsConfigure))
                            @foreach($goodsConfigure as $configure)
                                <tr>
                                    <th scope="row">
                                        <div class="media align-items-center">
                                            <div class="media-body">
                                                <span class="mb-0 text-sm">{{$configure->title}}</span>
                                            </div>
                                        </div>
                                    </th>
                                    <td>
                                        {{$configure->getGood->count()}}
                                    </td>
                                    <td>
                      <span class="badge badge-dot mr-4">
                          {{$configure->time}}
                      </span>
                                    </td>
                                    <td class="text-left">
                                        <div class="dropdown">
                                            <a class="btn btn-sm btn-icon-only text-light" href="#" role="button"
                                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="fas fa-ellipsis-v"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                <a class="dropdown-item"
                                                   href="{{route('admin.good.configure.edit',['id'=>$configure->id])}}">编辑</a>
                                                <a class="dropdown-item" onclick="event.preventDefault();
                                                    document.getElementById('del-goods-configure-{{$configure->id}}').submit();"
                                                   href="">删除</a>

                                                <form id="del-goods-configure-{{$configure->id}}"
                                                      action="{{ route('admin.good.configure.del') }}" method="POST"
                                                      style="display: none;">
                                                    {{csrf_field()}}
                                                    <input type="hidden" name="id" value="{{$configure->id}}">
                                                </form>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
                <div class="card-footer py-4">
                    {{--<a href="{{route('admin.good.configure.add')}}" class="btn btn-primary">新增配置</a>--}}
                    <a href="{{route('admin.good.configure.add',['type'=>'virtual_host'])}}" class="btn btn-primary">新增空间配置</a>
                    <a href="{{route('admin.good.configure.add',['type'=>'virtual_private_server'])}}"
                       class="btn btn-neutral">新增VPS配置</a>
                    <a href="" onclick="swal('未完成','该功能未完成','error')" class="btn btn-success">新增代理配置</a>
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection