routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//登陆 登出 注册 视图和操作

// Password Reset Routes...
//Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
//Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
//Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
//Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
//Route::get('auth/reset/pass', 'IndexController@resetFormPage')->name('password.request');

Route::middleware(['check.install.status', 'throttle:60,1'])->group(function () {//安装路由
    //Install
    Route::get('install/init', 'InstallController@installPage'); //Install View
    Route::post('install/init', 'InstallController@installAction');//Install Action
});


Route::middleware(['throttle:60,1','check.install.status'])->group(function () {
    Route::get('/', "IndexController@indexPage");//首页视图
    //Goods Show Page
    Route::get('goods/show', 'IndexController@goodShowPage')->name('good.show');//商品列表Goods Show Page
    //User email　validate
    Route::get('user/email/validate/{id}/{token}','IndexController@userEmailTokenValidate')->where(['id' => '^[0-9]*$']);
    //Diy page view
    Route::get('page/{hash}','DiyPageController@indexPage')->name('diy_page');
});

Route::middleware(['guest','throttle:60,1'])->group(function (){
    //Login
    Route::get('login', 'IndexController@loginPage')->name('login');//登陆视图 Login View
    Route::post('login', 'Auth\LoginController@login');//登陆操作 Login View
    //Register
    Route::get('register', 'IndexController@registerPage')->name('register');//注册视图 Register View
    Route::post('register', 'Auth\RegisterController@register');//注册操作 Register View
});
// wecaht/order/notify /alipay/order/notify /diy/order/notify
Route::any('/{payment}/order/notify', 'Payment\PayController@notify');//支付回调
Route::get('/temp/cron', "IndexController@tempCronAction");//临时监控

Route::prefix('admin')->group(function () {//管理路由
    Route::middleware(['auth', 'check.admin.authority', 'throttle:60,1'])->group(function () {
        Route::name('admin.')->group(function () {

            Route::get('/', 'AdminController@indexPage')->name('home');//Home Index View

            Route::prefix('user')->group(function () { //User Setting
                //Show
                Route::get('show', 'AdminController@userShowPage')->name('user.show');
                //Add
                Route::get('add', 'AdminController@userEditPage');
                Route::post('add', 'AdminController@userEditPage');
                //Edit
                Route::get('edit/{id}', 'AdminController@userEditPage')->name('user.edit');
                Route::post('edit', 'UserController@userEditAction');
            });

            Route::prefix('order')->group(function () { //订单 Order
                Route::get('show', 'AdminController@orderShowPage')->name('order.show');
                Route::get('edit/{no}', 'AdminController@orderEditPage')->name('order.edit');
                Route::post('edit', 'OrderController@orderEditAction');
            });
            Route::prefix('host')->group(function () { //主机 Host
                //Show
                Route::get('show', 'AdminController@hostShowPage')->name('host.show');
                //Recreate host action
                Route::post('create/host/re', 'HostController@reCreateHost')->where(['id' => '^[0-9]*$']);
                //Host Edit
                Route::get('detailed/{id}','AdminController@hostDetailedPage')->where(['id' => '^[0-9]*$'])->name('host.detailed');
                Route::post('detailed','HostController@hostEditAction');
                //host manager
                Route::post('open','HostController@openHost')->name('host.open');
                Route::post('close','HostController@closeHost')->name('host.close');
                Route::post('terminate','HostController@terminateHost')->name('host.terminate');
            });
            Route::prefix('work/order')->group(function () { //工单 Work order
                //show
                Route::get('show', 'AdminController@workOrderShowPage')->name('work.order.show');
                //Work order dateiled
                Route::get('detailed/{id}', 'AdminController@workOrderDetailedPage')->name('work.order.detailed')->where(['id' => '^[0-9]*$']);
                //Work order close
                Route::post('close', 'WorkOrderController@workOrderCloseAction')->name('work.order.close');
                //Work order reply
                Route::post('reply', 'WorkOrderController@workOrderAdminReplyAction')->name('work.order.reply');
            });
            Route::prefix('new')->group(function () { //新闻 news
                //show
                Route::get('show', 'AdminController@newShowPage')->name('new.show');
                //add
                Route::get('add', 'AdminController@newAddPage')->name('new.add');
                Route::post('add', 'NewController@newAddAction');
                //edit
                Route::get('edit/{id}', 'AdminController@newEditAction')->name('new.edit');
                Route::post('edit', 'NewController@newEditAction');
                //del
                Route::post('del', 'NewController@newDelAction')->name('new.del');
            });
            Route::prefix('good')->group(function () { //商品
                //Goods categories list
                Route::get('show', 'AdminController@goodShowPage')->name('good.show');
                //Goods categories add
                Route::get('categories/add', 'AdminController@goodCategoriesAddPage')->name('good.categories.add');
                Route::post('categories/add', 'GoodController@goodCategoriesAddAction');
                //Goods categories edit
                Route::get('categories/edit/{id}', 'AdminController@goodCategoriesEditPage')->name('good.categories.edit')->where(['id' => '^[0-9]*$']);
                Route::post('categories/edit', 'GoodController@goodCategoriesEditAction');
                //Goods categories del
                Route::post('categories/del', 'GoodController@goodCategoriesDelAction')->name('good.categories.del');
                //Goods configure add
                Route::get('configure/add/{type}', 'AdminController@goodConfigureAddPage')->name('good.configure.add');
                Route::post('configure/add', 'GoodConfigureController@goodConfigureAddAction');
                //Goods configure del
                Route::post('configure/del', 'GoodConfigureController@goodConfigureDelAction')->name('good.configure.del');
                //Goods configure edit
                Route::get('configure/edit/{id}', 'AdminController@goodConfigureEditPage')->name('good.configure.edit')->where(['id' => '^[0-9]*$']);
                Route::post('configure/edit', 'GoodConfigureController@goodConfigureEditAction');
                //Goods add
                Route::get('add', 'AdminController@goodAddPage')->name('good.add');
                Route::post('add', 'GoodController@goodAddAction');
                //Goods Edit
                Route::get('edit/{id}', 'AdminController@goodEditPage')->name('good.edit');
                Route::get('edit', 'AdminController@userEditPage');
                Route::post('edit', 'GoodController@goodEditAction');

                Route::get('charging/{id}','AdminController@goodChargingPage')->name('good.charging');
                Route::post('charging/edit','GoodController@goodChargingEdit')->name('good.charging.edit');
                Route::post('charging/add','GoodController@goodChargingAdd')->name('good.charging.add');
                Route::post('charging/del','GoodController@goodChargingDel')->name('good.charging.del');
                //Goods Del
                Route::post('del', 'GoodController@goodDelAction')->name('good.del');
            });

            Route::prefix('setting')->group(function () { //全局设置
                Route::get('/', 'AdminController@settingIndexPage')->name('setting.index');
                Route::post('/', 'AdminController@settingEditAction');
                //Payment Setting
                Route::get('{payment}/pay/config', 'AdminController@paymentPluginConfigPage')->name('setting.pay');
                Route::post('pay/config', 'Payment\PayController@paymentPluginConfigAction');
                //Mail Setting
                Route::get('mail/config','AdminController@mailDriveConfigPage')->name('setting.mail');
                Route::post('mail/config','MailDrive\UserMailController@mailDriveConfigAction');
                //Wechat Setting
                Route::get('wechat/config','AdminController@wechatConfigPage')->name('setting.wechat');
                Route::post('wechat/config','Wechat\WechatController@wechatConfigAction');
            });
            Route::prefix('server')->group(function () { //服务器设置
                //Show
                Route::get('show', 'AdminController@serverShowPage')->name('server.show');
                //Status
                Route::get('status/{id}', 'ServerController@serverStatusPage')->name('server.status')->where(['id' => '^[0-9]*$']);
                //Add
                Route::get('add', 'AdminController@serverAddPage')->name('server.add');
                Route::post('add', 'ServerController@serverAddAction');
                //Edit
                Route::get('edit/{id}', 'AdminController@serverEditPage')->name('server.edit')->where(['id' => '^[0-9]*$']);

resources/views/admin/themes/default/setting/mail.blade.php
@extends('admin.themes.default.layouts.app')

@section('content')
    @include('admin.themes.default.layouts.header')
@endsection

@section('container-fluid')
    <div class="row">
        <div class="col-xl-12 order-xl-1">
            <div class="card bg-secondary shadow">
                <div class="card-header bg-white border-0">
                    <div class="row align-items-center">
                        <div class="col-12">
                            <h3 class="mb-0">编辑插件配置</h3>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <form method="post" id="add-form" action="{{route('admin.setting.mail')}}">
                        {{csrf_field()}}
                        <h6 class="heading-small text-muted mb-4">邮件驱动配置信息</h6>
                        @if(!empty($form))
                            @foreach($form as $title=>$value)
                                <div class="pl-lg-4">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label class="form-control-label"
                                                       for="input-username">{{$title}}</label>
                                                <input type="text" class="form-control form-control-alternative"
                                                       value="{{old($title)? old($title):$setting->where('name',$value)->first()->value }}"
                                                       name={{$title}} >
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        @endif
                        @include('admin.themes.default.layouts.errors')
                        <input type="submit" class="btn btn-primary" value="保存">
                    </form>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/themes/default/setting/pay.blade.php
@extends('admin.themes.default.layouts.app')

@section('content')
    @include('admin.themes.default.layouts.header')
@endsection

@section('container-fluid')
    <div class="row">
        <div class="col-xl-12 order-xl-1">
            <div class="card bg-secondary shadow">
                <div class="card-header bg-white border-0">
                    <div class="row align-items-center">
                        <div class="col-12">
                            <h3 class="mb-0">编辑插件配置</h3>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <form method="post" id="add-form" action="{{action('Payment\PayController@paymentPluginConfigAction')}}">
                        {{csrf_field()}}
                        <input type="hidden" value="{{$payment}}" name="payment">
                        <h6 class="heading-small text-muted mb-4">支付插件配置信息</h6>
                        @if(!empty($form))
                            @foreach($form as $title=>$value)
                                <div class="pl-lg-4">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label class="form-control-label"
                                                       for="input-username">{{$title}}</label>
                                                <input type="text" class="form-control form-control-alternative"
                                                       value="{{old($title)? old($title):$setting->where('name',$value)->first()->value }}"
                                                       name={{$title}} >
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        @endif
                        @include('admin.themes.default.layouts.errors')
                        <input type="submit" class="btn btn-primary" value="保存">
                    </form>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/themes/default/setting/sms.blade.php
@extends('admin.themes.default.layouts.app')

@section('content')
    @include('admin.themes.default.layouts.header')
@endsection

@section('container-fluid')
    <div class="row">
        <div class="col-xl-12 order-xl-1">
            <div class="card bg-secondary shadow">
                <div class="card-header bg-white border-0">
                    <div class="row align-items-center">
                        <div class="col-12">
                            <h3 class="mb-0">编辑插件配置</h3>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <form method="post" id="add-form" action="{{route('admin.setting.mail')}}">
                        {{csrf_field()}}
                        <h6 class="heading-small text-muted mb-4">邮件驱动配置信息</h6>
                        @if(!empty($form))
                            @foreach($form as $title=>$value)
                                <div class="pl-lg-4">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label class="form-control-label"
                                                       for="input-username">{{$title}}</label>
                                                <input type="text" class="form-control form-control-alternative"
                                                       value="{{old($title)? old($title):$setting->where('name',$value)->first()->value }}"
                                                       name={{$title}} >
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        @endif
                        @include('admin.themes.default.layouts.errors')
                        <input type="submit" class="btn btn-primary" value="保存">
                    </form>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/themes/default/setting/wechat.blade.php
@extends('admin.themes.default.layouts.app')

@section('content')
    @include('admin.themes.default.layouts.header')
@endsection

@section('container-fluid')
    <div class="row">
        <div class="col-xl-12 order-xl-1">
            <div class="card bg-secondary shadow">
                <div class="card-header bg-white border-0">
                    <div class="row align-items-center">
                        <div class="col-12">
                            <h3 class="mb-0">微信配置设置</h3>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <form method="post" id="add-form" action="{{route('admin.setting.wechat')}}">
                        {{csrf_field()}}
                        @if(!empty($form))
                            @foreach($form as $classForms)
                                @foreach($classForms as $key=> $classForm )
                                    <h6 class="heading-small text-muted mb-4">{{$key}}</h6>
                                    @foreach($classForm as $title=>$value)
                                        <div class="pl-lg-4">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label class="form-control-label"
                                                               for="input-username">{{$title}}</label>
                                                        <input type="text" class="form-control form-control-alternative"
                                                               value="{{old($title)? old($title):$setting->where('name',$value)->first()->value }}"
                                                               name={{$title}} >
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    @endforeach
                                @endforeach
                            @endforeach
                        @endif
                        @include('admin.themes.default.layouts.errors')
                        <input type="submit" class="btn btn-primary" value="保存">
                    </form>
                </div>

            </div>
        </div>
    </div>
@endsection